QUOTES = [
    "Talk is cheap. Show me the code. - Linus Torvalds",
    "Programs must be written for people to read, and only incidentally for machines to execute. - Harold Abelson",
    "The best way to predict the future is to invent it. - Alan Kay",
    "Simplicity is the soul of efficiency. - Austin Freeman",
    "Make it work, make it right, make it fast. - Kent Beck",
    "Code is like humor. When you have to explain it, it’s bad. - Cory House",
    "Fix the cause, not the symptom. - Steve Maguire",
    "Optimism is an occupational hazard of programming: feedback is the treatment. - Kent Beck",
    "When to use iterative development? You should use iterative development only on projects that you want to succeed. - Martin Fowler",
    "Simplicity is prerequisite for reliability. - Edsger W. Dijkstra",
    "Software is eating the world. - Marc Andreessen",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Stay hungry, stay foolish. - Steve Jobs",
    "Innovation distinguishes between a leader and a follower. - Steve Jobs",
    "It's not a bug, it's a feature. - Anonymous",
    "Deleted code is debugged code. - Jeff Sickel",
    "Walking on water and developing software from a specification are easy if both are frozen. - Edward V. Berard",
    "There are only two kinds of languages: the ones people complain about and the ones nobody uses. - Bjarne Stroustrup",
    "Java is to JavaScript what car is to Carpet. - Chris Heilmann",
    "Premature optimization is the root of all evil. - Donald Knuth",
    "Good design adds value faster than it adds cost. - Thomas C. Gale",
    "Computers are good at following instructions, but not at reading your mind. - Donald Knuth",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. - Martin Fowler",
    "Programming is not about typing, it's about thinking. - Rich Hickey",
    "The most disastrous thing that you can ever learn is your first programming language. - Alan Kay",
    "AI is the new electricity. - Andrew Ng",
    "Artificial intelligence will reach human levels by around 2029. - Ray Kurzweil",
    "Predicting the future isn't magic, it's artificial intelligence. - Dave Waters",
    "Machine intelligence is the last invention that humanity will ever need to make. - Nick Bostrom",
    "Robots are not going to replace humans, they are going to make their jobs much more humane. - Sabine Hauert",
    "The development of full artificial intelligence could spell the end of the human race. - Stephen Hawking",
    "Data is the new oil. - Clive Humby",
    "Errors using inadequate data are much less than those using no data at all. - Charles Babbage",
    "Without data, you're just another person with an opinion. - W. Edwards Deming",
    "Torture the data, and it will confess to anything. - Ronald Coase",
    "Data really powers everything that we do. - Jeff Weiner",
    "Learning never exhausts the mind. - Leonardo da Vinci",
    "Live as if you were to die tomorrow. Learn as if you were to live forever. - Mahatma Gandhi",
    "The capacity to learn is a gift; the ability to learn is a skill; the willingness to learn is a choice. - Brian Herbert",
    "Change is the end result of all true learning. - Leo Buscaglia",
    "Tell me and I forget, teach me and I may remember, involve me and I learn. - Benjamin Franklin",
    "Develop a passion for learning. If you do, you will never cease to grow. - Anthony J. D'Angelo",
    "Dream big and dare to fail. - Norman Vaughan",
    "It always seems impossible until it's done. - Nelson Mandela",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "Act as if what you do makes a difference. It does. - William James",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Constraint inspires creativity. - Biz Stone",
    "Move fast and break things. - Mark Zuckerberg",
    "Done is better than perfect. - Sheryl Sandberg",
    "Focus on the user and all else will follow. - Google",
    "Creativity is intelligence having fun. - Albert Einstein",
    "What new technology does is create new opportunities to do a job that customers want done. - Tim O'Reilly",
    "Technology is best when it brings people together. - Matt Mullenweg",
    "It’s not about ideas. It’s about making ideas happen. - Scott Belsky",
    "Do not fear failure but rather fear not trying. - Roy T. Bennett",
    "If you are not willing to risk the usual, you will have to settle for the ordinary. - Jim Rohn",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "Opportunities don't happen. You create them. - Chris Grosser",
    "Try not to become a man of success. Rather become a man of value. - Albert Einstein",
    "Stop chasing the money and start chasing the passion. - Tony Hsieh",
    "All progress takes place outside the comfort zone. - Michael John Bobak",
    "The ones who are crazy enough to think they can change the world, are the ones who do. - Steve Jobs",
    "Don't let yesterday take up too much of today. - Will Rogers",
    "You learn more from failure than from success. Don't let it stop you. Failure builds character. - Unknown",
    "Experience is simply the name we give our mistakes. - Oscar Wilde",
    "Knowledge is power. - Francis Bacon",
    "May the Source be with you. - Anonymous",
    "Real programmers don't comment their code. If it was hard to write, it should be hard to understand. - Anonymous (Joke)",
    "Hardware: The parts of a computer system that can be kicked. - Jeff Pesis",
    "Software: The parts of a computer system that usually fail. - Unknown",
    "There are 10 types of people in the world: those who understand binary, and those who don't. - Anonymous",
    "Programming today is a race between software engineers striving to build bigger and better idiot-proof programs, and the Universe trying to produce bigger and better idiots. So far, the Universe is winning. - Rick Cook",
    "One man's crappy software is another man's full time job. - Jessica Gaston",
    "A good programmer is someone who always looks both ways before crossing a one-way street. - Doug Linder",
    "Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live. - John Woods",
    "Truth can only be found in one place: the code. - Robert C. Martin",
    "Clean code always looks like it was written by someone who cares. - Robert C. Martin",
    "Refactoring is just like cleaning the kitchen: you don't earn money by doing it, but if you don't do it, you can't cook anymore. - Anonymous",
    "Documentation is like sex: when it is good, it is very, very good; and when it is bad, it is better than nothing. - Dick Brandon",
    "Before software can be reusable it first has to be usable. - Ralph Johnson",
    "If debugging is the process of removing software bugs, then programming must be the process of putting them in. - Edsger Dijkstra",
    "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. - Bill Gates",
    "Controlling complexity is the essence of computer programming. - Brian Kernighan"
]
