# 工作流的名称
name: Daily AI Paper Briefing

# 触发条件
on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *' # 北京时间早上9点

# 任务
jobs:
  run-daily-briefing:
    runs-on: windows-latest
    
    defaults:
      run:
        shell: powershell
    
    env:
      ZHIPUAI_API_KEY: ${{ secrets.ZHIPUAI_API_KEY }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      TO_EMAIL: ${{ secrets.TO_EMAIL }}
    
    steps:
      - name: 1. Checkout repository code
        uses: actions/checkout@v4
      
      - name: 2. Set up Python 3.11.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'
      
      - name: 3. Install dependencies
        run: .\install_env.bat
      
      - name: 4. Run main pipeline script
        id: run_script
        # 添加错误处理，但不让错误中断工作流
        continue-on-error: true
        run: .\hf-paper-env\Scripts\python.exe run_pipeline.py --rageMode
      
      # 发送邮件通知的步骤 (改进版)
      - name: 5. Send email notification
        if: always()
        # 邮件发送失败不应该影响工作流状态
        continue-on-error: true
        run: |
          Write-Host "📧 准备发送邮件通知，任务状态: ${{ job.status }}"
          .\hf-paper-env\Scripts\python.exe send_email.py ${{ job.status }}
