# 工作流的名称
name: Daily AI Paper Briefing

# 触发条件
on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *' # 北京时间早上9点

# 任务
jobs:
  run-daily-briefing:
    runs-on: windows-latest

    # 默认 shell 仍然是 powershell，这是正确的选择
    defaults:
      run:
        shell: powershell

    env:
      ZHIPUAI_API_KEY: ${{ secrets.ZHIPUAI_API_KEY }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      TO_EMAIL: ${{ secrets.TO_EMAIL }}

    steps:
      - name: 1. Checkout repository code
        uses: actions/checkout@v4

      - name: 2. Set up Python 3.11.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'

      - name: 3. Install dependencies
        # --- 关键改动：使用新的文件名和正确的 PowerShell 语法 ---
        run: .\install_env.bat
      
      - name: 4. Run main pipeline script
        id: run_script
        # --- 关键改动：使用新的文件名和正确的 PowerShell 语法 ---
        run: .\activate_env.bat; python run_pipeline.py --rageMode
      
      # 发送邮件通知的步骤 (最终修正版)
      - name: 5. Send email notification
        if: always()
        # --- 关键改动：使用新的文件名和正确的 PowerShell 语法 ---
        run: .\activate_env.bat; python send_email.py ${{ job.status }}
