# 工作流的名称
name: Daily AI Paper Briefing

# 触发条件
on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *' # 北京时间早上9点

# 任务
jobs:
  run-daily-briefing:
    runs-on: windows-latest

    # 设置默认的 shell 和工作目录，这是更稳妥的做法
    defaults:
      run:
        shell: cmd
        working-directory: ${{ github.workspace }}

    env:
      ZHIPUAI_API_KEY: ${{ secrets.ZHIPUAI_API_KEY }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      TO_EMAIL: ${{ secrets.TO_EMAIL }}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.11.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'

      # 这个步骤现在会继承 defaults 设置，自动在正确的目录下运行
      - name: Install dependencies via BAT file
        run: .\安装环境.bat

      # 这个步骤同样继承 defaults
      - name: Activate environment and run main script
        id: run_script
        run: |
          call .\启动环境.bat
          python run_pipeline.py --rageMode
      
      # 发送邮件通知的步骤 (已修正)
      - name: Send email notification
        if: always()
        run: |
          echo "Preparing to send email notification for job status: ${{ job.status }}"
          python send_email.py ${{ job.status }}
