# 工作流的名称
name: Daily AI Paper Briefing

# 触发条件
on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *' # 北京时间早上9点

# 任务
jobs:
  run-daily-briefing:
    runs-on: windows-latest

    env:
      ZHIPUAI_API_KEY: ${{ secrets.ZHIPUAI_API_KEY }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      TO_EMAIL: ${{ secrets.TO_EMAIL }}

    steps:
      - name: 1. Checkout repository code
        uses: actions/checkout@v4

      - name: 2. Set up Python 3.11.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'

      - name: 3. Install dependencies via BAT file
        shell: cmd
        run: .\安装环境.bat
      
      - name: 4. Run main pipeline script
        id: run_script
        shell: cmd
        run: |
          echo "call .\\启动环境.bat" > temp_run_main.bat
          echo "python run_pipeline.py --rageMode" >> temp_run_main.bat
          call temp_run_main.bat
      
      # 发送邮件通知的步骤 (已修正复制粘贴错误)
      - name: 5. Send email notification
        if: always()
        shell: cmd
        run: |
          echo "call .\\启动环境.bat" > temp_run_email.bat
          echo "python send_email.py ${{ job.status }}" >> temp_run_email.bat
          call temp_run_email.bat
