name: Daily AI Paper Briefing

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'  # UTC 1:00 AM = Beijing 9:00 AM

jobs:
  run-daily-briefing:
    runs-on: windows-latest
    
    env:
      ZHIPUAI_API_KEY: ${{ secrets.ZHIPUAI_API_KEY }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      TO_EMAIL: ${{ secrets.TO_EMAIL }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'
      
      - name: Install dependencies
        shell: cmd
        run: install_env.bat
      
      - name: Run pipeline
        id: pipeline
        continue-on-error: true
        shell: cmd
        run: hf-paper-env\Scripts\python.exe run_pipeline.py --rageMode
      
      - name: Send notification
        if: always()
        continue-on-error: true
        shell: cmd
        run: hf-paper-env\Scripts\python.exe send_email.py ${{ job.status }}
